//! User, assistant, and error event payloads.

use serde::{Deserialize, Serialize};

/// User-authored text recorded by the runtime.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UserMessage {
    pub content: String,
}

impl UserMessage {
    pub fn new(content: impl Into<String>) -> Self {
        Self {
            content: content.into(),
        }
    }
}

/// Assistant text recorded for display.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AssistantMessage {
    pub content: String,
    pub source: AssistantMessageSource,
}

impl AssistantMessage {
    pub fn new(content: impl Into<String>, source: AssistantMessageSource) -> Self {
        Self {
            content: content.into(),
            source,
        }
    }
}

/// Where assistant text came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AssistantMessageSource {
    /// Text generated by controller-owned logic.
    Controller,
    /// Text generated from runtime-verified state, not provider memory.
    VerifiedState,
    /// Text returned by a provider. This is never filesystem or action truth.
    Provider,
}

/// Error state recorded by the controller.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ErrorEvent {
    pub message: String,
}

impl ErrorEvent {
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}
