//! Core event types recorded by Elgar.
//!
//! Events are the runtime facts that CLI, TUI, logs, and tests can render or
//! inspect. They describe what Elgar recorded; provider output is not treated as
//! proof that files changed or commands ran.

#[cfg(test)]
mod tests;

use serde::{Deserialize, Serialize};

use crate::{
    provider::{ChatToolCall, ProviderBackendKind, ProviderReasoningLevel},
    token_accounting::ProviderTokenUsage,
};

/// A core-recorded fact that can be rendered by CLI, TUI, or tests.
///
/// Events are not provider wishes. In particular, provider output is captured
/// only as provider output; it does not prove that a file changed, a command ran,
/// or an action moved through its lifecycle.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Event {
    /// The runtime recorded input received from the user.
    UserMessage(UserMessage),
    /// The runtime or action gate recorded assistant text for display.
    AssistantMessage(AssistantMessage),
    /// The runtime started a provider request.
    ProviderStarted(ProviderStarted),
    /// The runtime received provider output.
    ProviderFinished(ProviderFinished),
    /// The core recorded an error.
    Error(ErrorEvent),
}

/// User-authored text recorded by the runtime.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UserMessage {
    pub content: String,
}

impl UserMessage {
    pub fn new(content: impl Into<String>) -> Self {
        Self {
            content: content.into(),
        }
    }
}

/// Assistant text recorded for display.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AssistantMessage {
    pub content: String,
    pub source: AssistantMessageSource,
}

impl AssistantMessage {
    pub fn new(content: impl Into<String>, source: AssistantMessageSource) -> Self {
        Self {
            content: content.into(),
            source,
        }
    }
}

/// Where assistant text came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AssistantMessageSource {
    /// Text generated by controller-owned logic.
    Controller,
    /// Text generated from runtime-verified state, not provider memory.
    VerifiedState,
    /// Text returned by a provider. This is never filesystem or action truth.
    Provider,
}

/// A provider request started by the runtime.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProviderStarted {
    pub provider: String,
    pub request_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub request_mode: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_count: Option<usize>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub backend: Option<ProviderBackendKind>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<ProviderReasoningLevel>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context_length: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stats: Option<bool>,
}

impl ProviderStarted {
    pub fn new(provider: impl Into<String>, request_id: impl Into<String>) -> Self {
        Self {
            provider: provider.into(),
            request_id: request_id.into(),
            model: None,
            request_mode: None,
            tool_count: None,
            backend: None,
            reasoning: None,
            context_length: None,
            stats: None,
        }
    }

    pub fn with_request_details(
        mut self,
        model: Option<String>,
        request_mode: impl Into<String>,
        tool_count: usize,
    ) -> Self {
        self.model = model;
        self.request_mode = Some(request_mode.into());
        self.tool_count = Some(tool_count);
        self
    }

    pub fn with_provider_profile(
        mut self,
        backend: Option<ProviderBackendKind>,
        reasoning: Option<ProviderReasoningLevel>,
        context_length: Option<u64>,
        stats: Option<bool>,
    ) -> Self {
        self.backend = backend;
        self.reasoning = reasoning;
        self.context_length = context_length;
        self.stats = stats;
        self
    }
}

/// Provider output received by the controller.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProviderFinished {
    pub provider: String,
    pub request_id: String,
    pub output: ProviderOutput,
}

impl ProviderFinished {
    pub fn new(
        provider: impl Into<String>,
        request_id: impl Into<String>,
        output: ProviderOutput,
    ) -> Self {
        Self {
            provider: provider.into(),
            request_id: request_id.into(),
            output,
        }
    }
}

/// Text returned by a provider.
///
/// This may contain suggestions or claims, but it is not proof that anything
/// happened outside the provider response.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProviderOutput {
    pub text: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tool_calls: Vec<ChatToolCall>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thinking: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metrics: Option<ProviderMetrics>,
}

impl ProviderOutput {
    pub fn new(text: impl Into<String>) -> Self {
        Self {
            text: text.into(),
            tool_calls: Vec::new(),
            thinking: None,
            metrics: None,
        }
    }

    pub fn with_tool_calls(mut self, tool_calls: Vec<ChatToolCall>) -> Self {
        self.tool_calls = tool_calls;
        self
    }

    pub fn with_thinking(mut self, thinking: impl Into<String>) -> Self {
        self.thinking = Some(thinking.into());
        self
    }

    pub fn with_metrics(mut self, metrics: ProviderMetrics) -> Self {
        self.metrics = Some(metrics);
        self
    }
}

/// Provider-owned facts about one provider request.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProviderMetrics {
    pub request_id: String,
    pub model: Option<String>,
    pub stream: bool,
    pub message_count: usize,
    pub serialized_request_bytes: usize,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub backend: Option<ProviderBackendKind>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<ProviderReasoningLevel>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context_length: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stats: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider_time_to_first_token_millis: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider_tokens_per_second_milli: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning_output_tokens: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage: Option<ProviderTokenUsage>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub first_chunk_latency_millis: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_duration_millis: Option<u64>,
}

impl ProviderMetrics {
    pub fn new(
        request_id: impl Into<String>,
        model: Option<String>,
        stream: bool,
        message_count: usize,
        serialized_request_bytes: usize,
    ) -> Self {
        Self {
            request_id: request_id.into(),
            model,
            stream,
            message_count,
            serialized_request_bytes,
            backend: None,
            reasoning: None,
            context_length: None,
            stats: None,
            provider_time_to_first_token_millis: None,
            provider_tokens_per_second_milli: None,
            reasoning_output_tokens: None,
            usage: None,
            first_chunk_latency_millis: None,
            total_duration_millis: None,
        }
    }
}

/// Error state recorded by the controller.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ErrorEvent {
    pub message: String,
}

impl ErrorEvent {
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}
