use serde::{Deserialize, Serialize};

pub use crate::action::ActionKind;

/// A controller-recorded fact that can be rendered by CLI, TUI, or tests.
///
/// Events are not provider wishes. In particular, provider output is captured
/// only as provider output; it does not prove that a file changed, a command ran,
/// or an action moved through its lifecycle.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Event {
    /// The controller recorded input received from the user.
    UserMessage(UserMessage),
    /// The controller recorded assistant text for display.
    AssistantMessage(AssistantMessage),
    /// The controller started a provider request.
    ProviderStarted(ProviderStarted),
    /// The controller received provider output.
    ProviderFinished(ProviderFinished),
    /// The controller created a proposed action.
    ActionProposed(ActionEvent),
    /// The controller recorded user approval for a proposed action.
    ActionApproved(ActionEvent),
    /// The controller recorded user rejection for a proposed action.
    ActionRejected(ActionEvent),
    /// The controller recorded a verified applied action result.
    ActionApplied(ActionApplied),
    /// The controller recorded that an action failed.
    ActionFailed(ActionFailed),
    /// The controller recorded an error.
    Error(ErrorEvent),
}

/// User-authored text recorded by the controller.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UserMessage {
    pub content: String,
}

impl UserMessage {
    pub fn new(content: impl Into<String>) -> Self {
        Self {
            content: content.into(),
        }
    }
}

/// Assistant text recorded for display.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AssistantMessage {
    pub content: String,
    pub source: AssistantMessageSource,
}

impl AssistantMessage {
    pub fn new(content: impl Into<String>, source: AssistantMessageSource) -> Self {
        Self {
            content: content.into(),
            source,
        }
    }
}

/// Where assistant text came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AssistantMessageSource {
    /// Text generated by controller-owned logic.
    Controller,
    /// Text returned by a provider. This is never filesystem or action truth.
    Provider,
}

/// A provider request started by the controller.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProviderStarted {
    pub provider: String,
    pub request_id: String,
}

impl ProviderStarted {
    pub fn new(provider: impl Into<String>, request_id: impl Into<String>) -> Self {
        Self {
            provider: provider.into(),
            request_id: request_id.into(),
        }
    }
}

/// Provider output received by the controller.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProviderFinished {
    pub provider: String,
    pub request_id: String,
    pub output: ProviderOutput,
}

impl ProviderFinished {
    pub fn new(
        provider: impl Into<String>,
        request_id: impl Into<String>,
        output: ProviderOutput,
    ) -> Self {
        Self {
            provider: provider.into(),
            request_id: request_id.into(),
            output,
        }
    }
}

/// Text returned by a provider.
///
/// This may contain suggestions or claims, but it is not proof that anything
/// happened outside the provider response.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProviderOutput {
    pub text: String,
}

impl ProviderOutput {
    pub fn new(text: impl Into<String>) -> Self {
        Self { text: text.into() }
    }
}

/// A controller-owned lifecycle event for an action.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ActionEvent {
    pub action_id: String,
    pub action_kind: ActionKind,
    pub target: Option<String>,
    pub summary: String,
}

impl ActionEvent {
    pub fn new(
        action_id: impl Into<String>,
        action_kind: ActionKind,
        summary: impl Into<String>,
    ) -> Self {
        Self {
            action_id: action_id.into(),
            action_kind,
            target: None,
            summary: summary.into(),
        }
    }

    pub fn with_target(mut self, target: impl Into<String>) -> Self {
        self.target = Some(target.into());
        self
    }
}

/// A verified action application recorded by the controller.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ActionApplied {
    pub action_id: String,
    pub action_kind: ActionKind,
    pub result: VerifiedActionResult,
}

impl ActionApplied {
    pub fn new(
        action_id: impl Into<String>,
        action_kind: ActionKind,
        result: VerifiedActionResult,
    ) -> Self {
        Self {
            action_id: action_id.into(),
            action_kind,
            result,
        }
    }
}

/// Result that was confirmed by the component that owns the real-world state.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum VerifiedActionResult {
    /// The filesystem confirmed that a file was written at this path.
    FileWritten { path: String },
}

/// A failed action recorded by the controller.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ActionFailed {
    pub action_id: String,
    pub action_kind: ActionKind,
    pub reason: String,
}

impl ActionFailed {
    pub fn new(
        action_id: impl Into<String>,
        action_kind: ActionKind,
        reason: impl Into<String>,
    ) -> Self {
        Self {
            action_id: action_id.into(),
            action_kind,
            reason: reason.into(),
        }
    }
}

/// Error state recorded by the controller.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ErrorEvent {
    pub message: String,
}

impl ErrorEvent {
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}
