pub mod action;
pub mod agent_loop;
pub mod agent_runtime;
pub mod context;
pub mod controller;
mod controller_project_memory;
mod controller_prompt;
mod controller_provider;
mod controller_reporting;
mod controller_scaffold;
mod controller_shell_commands;
mod controller_shell_verify;
pub mod event;
mod followup_action_paths;
pub mod fs;
mod legacy_controller_model_first_apply;
mod legacy_controller_model_first_continuation;
mod legacy_controller_model_first_decision;
mod legacy_controller_model_first_plan_completion;
pub mod model_runtime;
pub mod policy;
pub mod provider;
mod provider_visible;
pub use provider_visible::provider_visible_text_from_text_only_output;
pub mod renderer;
pub mod router;
pub mod session;
pub mod shell;

pub const CORE_PHILOSOPHY: &str = "Controller owns truth. Model suggests. User approves. Filesystem confirms. UI reports. Tests protect. Extensions wait.";
